# Shades of Purple Colors
background            #2d2b55
foreground            #a599e9
cursor                #f3f99d
selection_background  #5d37a8
selection_foreground  #ffffff

# Transparency & Blur
background_opacity         0.85
background_blur            1

# Font (Fedora comes with JetBrains Mono usually)
font_family      JetBrains Mono
font_size        12.0

# Window padding
window_padding_width 10
